# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "nedap-wolfssl-mixin"
BBFILE_PATTERN_nedap-wolfssl-mixin = "^${LAYERDIR}/"
BBFILE_PRIORITY_nedap-wolfssl-mixin = "10"

LAYERDEPENDS_nedap-wolfssl-mixin = "core"
LAYERSERIES_COMPAT_nedap-wolfssl-mixin = "scarthgap"

LICENSE_PATH += "${LAYERDIR}/files/custom-licenses"
