# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-nedap-mixins"
BBFILE_PATTERN_meta-nedap-mixins = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-nedap-mixins = "10"

LAYERDEPENDS_meta-nedap-mixins = "core"
LAYERSERIES_COMPAT_meta-nedap-mixins = "scarthgap"
